/**
 * SecondBrainPage — thelyceum.site/secondbrain. Personal workspace for
 * accepted accounts (registration is vetted, so any signed-in account
 * qualifies): add your own documents and a weekly study schedule — built
 * by hand or generated by AI — then submit both as an "order" for the
 * Lyceum team to turn into a personalized plan (reviewed in the admin
 * "Orders" queue). Rendered as a standalone route (see App.tsx).
 */
import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import {
  listDocuments, saveDocument, type AuthoredDocMeta,
  generateAiSchedule, submitOrder, listMyOrders, type AiScheduleBlock, type OrderRecord,
} from '../lib/lyceumApi';
import { SUBJECT_META } from '../lib/persist';
import { LiquidMetalButton } from '../../components/ui/liquid-metal-button';

const DAY_LABELS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

function DocumentsSection({ docs, onAdded }: { docs: AuthoredDocMeta[]; onAdded: () => void }) {
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [busy, setBusy] = useState(false);

  async function add() {
    if (!title.trim() || !content.trim() || busy) return;
    setBusy(true);
    try {
      await saveDocument({ title: title.trim(), content: content.trim(), visibility: 'private' });
      setTitle(''); setContent('');
      onAdded();
    } finally { setBusy(false); }
  }

  return (
    <div className="glass-card rounded-3xl p-6">
      <p className="text-[10px] uppercase tracking-[2px] text-white/40 mb-1">Your documents</p>
      <p className="text-xs text-white/30 mb-4">Add material for the Lyceum team to build your plan around — private by default.</p>

      <div className="flex flex-col gap-2 mb-4">
        <input value={title} onChange={e => setTitle(e.target.value)} placeholder="Document title"
          className="bg-white/5 rounded-xl px-3 py-2.5 text-sm text-white/90 outline-none border border-white/10 focus:border-white/25" />
        <textarea value={content} onChange={e => setContent(e.target.value)} rows={4} placeholder="Paste content…"
          className="bg-white/5 rounded-xl px-3 py-2.5 text-sm text-white/90 outline-none border border-white/10 focus:border-white/25 resize-y" />
        <div className="flex justify-end">
          <button onClick={add} disabled={busy || !title.trim() || !content.trim()}
            className="glass-btn rounded-xl px-4 py-2 text-[10px] uppercase tracking-[2px] disabled:opacity-30">
            {busy ? 'Adding…' : 'Add document'}
          </button>
        </div>
      </div>

      {docs.length > 0 ? (
        <div className="flex flex-col gap-1.5">
          {docs.map(d => (
            <div key={d.id} className="flex items-center justify-between glass-pill rounded-xl px-3 py-2">
              <span className="text-xs text-white/75 truncate">📄 {d.title}</span>
              <span className="text-[9px] uppercase tracking-[1.5px] text-white/30">{d.folder || 'unfiled'}</span>
            </div>
          ))}
        </div>
      ) : (
        <p className="text-xs text-white/30">No documents yet.</p>
      )}
    </div>
  );
}

function ScheduleSection({ blocks, onChange }: { blocks: AiScheduleBlock[]; onChange: (b: AiScheduleBlock[]) => void }) {
  const [day, setDay] = useState(0);
  const [hour, setHour] = useState(18);
  const [subject, setSubject] = useState(Object.keys(SUBJECT_META)[0] || 'math');
  const [weeklyHours, setWeeklyHours] = useState(10);
  const [aiBusy, setAiBusy] = useState(false);
  const [error, setError] = useState('');

  function addBlock() {
    const startMinute = hour * 60;
    const next = blocks.filter(b => !(b.dayOfWeek === day && b.startMinute === startMinute));
    next.push({ id: `${day}-${startMinute}`, subjectKey: subject, dayOfWeek: day, startMinute, durationMinutes: 60 });
    onChange(next);
  }

  async function askAi() {
    setAiBusy(true); setError('');
    try {
      const subjectKeys = Object.keys(SUBJECT_META).filter(k => k !== 'other');
      const { blocks: aiBlocks } = await generateAiSchedule(weeklyHours, subjectKeys, []);
      if (aiBlocks.length === 0) { setError('AI could not suggest a schedule — try again or build one manually.'); return; }
      onChange(aiBlocks);
    } catch (e: any) {
      setError(e?.message || 'Something went wrong.');
    } finally { setAiBusy(false); }
  }

  const sorted = [...blocks].sort((a, b) => a.dayOfWeek - b.dayOfWeek || a.startMinute - b.startMinute);

  return (
    <div className="glass-card rounded-3xl p-6">
      <p className="text-[10px] uppercase tracking-[2px] text-white/40 mb-1">Study schedule</p>
      <p className="text-xs text-white/30 mb-4">Build your own weekly blocks, or let the AI suggest one.</p>

      <div className="flex flex-wrap items-center gap-2 mb-4">
        <input type="number" min={1} max={60} value={weeklyHours} onChange={e => setWeeklyHours(Number(e.target.value))}
          className="w-20 bg-white/5 rounded-xl px-3 py-2 text-xs text-white/85 outline-none border border-white/10" />
        <span className="text-xs text-white/40">hrs/week</span>
        <LiquidMetalButton label={aiBusy ? 'Thinking…' : '✨ AI suggest schedule'} onClick={askAi} />
      </div>
      {error && <p className="text-xs text-red-300/80 mb-3">{error}</p>}

      <div className="flex flex-wrap gap-2 mb-4">
        <select value={day} onChange={e => setDay(Number(e.target.value))}
          className="bg-white/5 rounded-xl px-3 py-2 text-xs text-white/85 outline-none border border-white/10">
          {DAY_LABELS.map((d, i) => <option key={d} value={i} className="bg-neutral-900">{d}</option>)}
        </select>
        <select value={hour} onChange={e => setHour(Number(e.target.value))}
          className="bg-white/5 rounded-xl px-3 py-2 text-xs text-white/85 outline-none border border-white/10">
          {Array.from({ length: 16 }, (_, i) => 6 + i).map(h => <option key={h} value={h} className="bg-neutral-900">{h}:00</option>)}
        </select>
        <select value={subject} onChange={e => setSubject(e.target.value)}
          className="bg-white/5 rounded-xl px-3 py-2 text-xs text-white/85 outline-none border border-white/10">
          {Object.entries(SUBJECT_META).map(([key, meta]) => <option key={key} value={key} className="bg-neutral-900">{meta.icon} {meta.label}</option>)}
        </select>
        <button onClick={addBlock} className="glass-btn rounded-xl px-4 py-2 text-[10px] uppercase tracking-[2px]">Add block</button>
      </div>

      {sorted.length === 0 ? (
        <p className="text-xs text-white/30">No blocks yet.</p>
      ) : (
        <div className="flex flex-col gap-1.5">
          {sorted.map(b => {
            const meta = SUBJECT_META[b.subjectKey];
            return (
              <div key={b.id} className="flex items-center justify-between glass-pill rounded-xl px-3 py-2">
                <span className="text-xs text-white/75">
                  {DAY_LABELS[b.dayOfWeek]} · {Math.floor(b.startMinute / 60)}:00 — {meta?.icon || ''} {meta?.label || b.subjectKey}
                </span>
                <button onClick={() => onChange(blocks.filter(x => x.id !== b.id))} className="opacity-40 hover:opacity-90">
                  <span className="material-symbols-outlined text-[14px]">close</span>
                </button>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

function MyOrders({ orders }: { orders: OrderRecord[] }) {
  if (orders.length === 0) return null;
  return (
    <div className="glass-card rounded-3xl p-6">
      <p className="text-[10px] uppercase tracking-[2px] text-white/40 mb-4">Your orders</p>
      <div className="flex flex-col gap-2">
        {orders.map(o => (
          <div key={o.id} className="flex items-center justify-between glass-pill rounded-xl px-3 py-2.5">
            <span className="text-xs text-white/70">
              {o.documents.length} doc{o.documents.length === 1 ? '' : 's'} · {o.schedule.length} block{o.schedule.length === 1 ? '' : 's'}
              {o.ai_generated ? ' · AI-suggested' : ''}
            </span>
            <span className={`text-[9px] uppercase tracking-[1.5px] px-2 py-0.5 rounded-full ${
              o.status === 'accepted' ? 'text-emerald-300 bg-emerald-400/10' :
              o.status === 'declined' ? 'text-red-300 bg-red-400/10' : 'text-amber-300 bg-amber-400/10'}`}>
              {o.status}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

export default function SecondBrainPage() {
  const { user, loading, devMode } = useAuth();
  const [docs, setDocs] = useState<AuthoredDocMeta[]>([]);
  const [blocks, setBlocks] = useState<AiScheduleBlock[]>([]);
  const [note, setNote] = useState('');
  const [orders, setOrders] = useState<OrderRecord[]>([]);
  const [submitting, setSubmitting] = useState(false);
  const [submitMsg, setSubmitMsg] = useState('');

  async function refreshAll() {
    const [d, o] = await Promise.all([listDocuments().catch(() => null), listMyOrders().catch(() => null)]);
    if (d) setDocs(d.mine);
    if (o) setOrders(o.orders);
  }
  useEffect(() => { if (user || devMode) refreshAll(); }, [user, devMode]);

  async function handleSubmitOrder() {
    if (submitting) return;
    setSubmitting(true); setSubmitMsg('');
    try {
      const wasAi = blocks.length > 0 && blocks.every(b => b.id.startsWith('ai-'));
      await submitOrder(docs.map(d => ({ id: d.id, title: d.title })), blocks, wasAi, note.trim());
      setSubmitMsg('Order submitted — the Lyceum team will follow up.');
      setNote('');
      await refreshAll();
    } catch (e: any) {
      setSubmitMsg(e?.message || 'Could not submit — please try again.');
    } finally { setSubmitting(false); }
  }

  if (loading) {
    return <div className="bg-[#050508] min-h-screen flex items-center justify-center text-slate-500 text-sm">Loading…</div>;
  }

  if (!user && !devMode) {
    return (
      <div className="bg-[#050508] text-slate-200 min-h-screen flex items-center justify-center px-4">
        <div className="glass-card rounded-3xl p-10 text-center max-w-sm">
          <h1 className="font-serif text-xl mb-2">Sign in required</h1>
          <p className="text-sm text-slate-400 mb-5">Your Startup Second Brain is only for accepted Lyceum founders.</p>
          <a href="/" className="text-sm text-purple-300 underline">Go to sign in</a>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-[#050508] text-slate-200 font-sans antialiased min-h-screen">
      <header className="max-w-2xl mx-auto px-4 pt-10 pb-6 flex items-center justify-between">
        <a href="/" className="font-serif text-lg tracking-[3px] uppercase text-slate-300">The Lyceum</a>
        <span className="text-xs uppercase tracking-[2px] text-purple-300">Startup Second Brain</span>
      </header>

      <main className="max-w-2xl mx-auto px-4 pb-20 flex flex-col gap-6">
        <div className="text-center mb-2">
          <h1 className="font-garamond text-3xl text-metallic mb-2">Your Startup Second Brain</h1>
          <p className="text-slate-400 text-sm max-w-md mx-auto">
            Add your documents and a study schedule — we'll turn it into a personalized plan for your startup.
          </p>
        </div>

        <DocumentsSection docs={docs} onAdded={refreshAll} />
        <ScheduleSection blocks={blocks} onChange={setBlocks} />

        <div className="glass-card rounded-3xl p-6">
          <p className="text-[10px] uppercase tracking-[2px] text-white/40 mb-3">Notes for the team (optional)</p>
          <textarea value={note} onChange={e => setNote(e.target.value)} rows={3}
            placeholder="Anything else we should know?"
            className="w-full bg-white/5 rounded-xl px-3 py-2.5 text-sm text-white/90 outline-none border border-white/10 focus:border-white/25 resize-y mb-4" />
          <div className="flex items-center justify-between">
            {submitMsg && <p className="text-xs text-emerald-300/80">{submitMsg}</p>}
            <div className="ml-auto">
              <LiquidMetalButton
                label={submitting ? 'Submitting…' : 'Submit order'}
                onClick={handleSubmitOrder}
              />
            </div>
          </div>
        </div>

        <MyOrders orders={orders} />
      </main>
    </div>
  );
}
